/**APP MODULE */
export const APP_MODULE = "app/";
export const APP_GETTER_NAV = APP_MODULE + "navigation";
export const APP_GETTER_USERNAME = APP_MODULE + "username";

/**ISSUES MODULE */
export const ISSUE_MODULE = "issues/";
export const ISSUE_GETTER_LIST = ISSUE_MODULE + "listItems";
export const ISSUE_GETTER_LIST_STATUS = ISSUE_MODULE + "listStatus";
export const ISSUE_GETTER_SHOW_MODE = ISSUE_MODULE + "showMode";
export const ISSUE_GETTER_USERS = ISSUE_MODULE + "users";
export const ISSUE_GETTER_FILTER_STATE = ISSUE_MODULE + "activeState";

export const ISSUE_ACTION = "ISSUE_ACTION";
export const ISSUE_REQUEST = "ISSUE_REQUEST";
export const ISSUE_SUCCESS = "ISSUE_SUCCESS";
export const ISSUE_FAILED = "ISSUE_FAILED";
export const ISSUE_CREATE_ACTION = "ISSUE_CREATE_ACTION";
export const ISSUE_CREATE_REQUEST = "ISSUE_CREATE_REQUEST";
export const ISSUE_CREATE_SUCCESS = "ISSUE_CREATE_SUCCESS";
export const ISSUE_CREATE_FAILED = "ISSUE_CREATE_FAILED";
export const ISSUE_EDIT_ACTION = "ISSUE_EDIT_ACTION";
export const ISSUE_EDIT_REQUEST = "ISSUE_EDIT_REQUEST";
export const ISSUE_EDIT_SUCCESS = "ISSUE_EDIT_SUCCESS";
export const ISSUE_EDIT_FAILED = "ISSUE_EDIT_FAILED";
export const ISSUE_RESOLVE_ACTION = "ISSUE_RESOLVE_ACTION";
export const ISSUE_RESOLVE_REQUEST = "ISSUE_RESOLVE_REQUEST";
export const ISSUE_RESOLVE_SUCCESS = "ISSUE_RESOLVE_SUCCESS";
export const ISSUE_RESOLVE_FAILED = "ISSUE_RESOLVE_FAILED";
export const ISSUE_DELETE_ACTION = "ISSUE_DELETE_ACTION";
export const ISSUE_DELETE_REQUEST = "ISSUE_DELETE_REQUEST";
export const ISSUE_DELETE_SUCCESS = "ISSUE_DELETE_SUCCESS";
export const ISSUE_DELETE_FAILED = "ISSUE_DELETE_FAILED";
export const ISSUE_FILER = "ISSUE_FILER";
export const ISSUE_FILER_TYPE = "ISSUE_FILER_TYPE";
export const ISSUE_FILER_SHOW = "ISSUE_FILER_SHOW";
export const ISSUE_MODULE_GETALL_ACTION = ISSUE_MODULE + ISSUE_ACTION;
export const ISSUE_MODULE_CREATE_ACTION = ISSUE_MODULE + ISSUE_CREATE_ACTION;
export const ISSUE_MODULE_EDIT_ACTION = ISSUE_MODULE + ISSUE_EDIT_ACTION;
export const ISSUE_MODULE_RESOLVE_ACTION = ISSUE_MODULE + ISSUE_RESOLVE_ACTION;
export const ISSUE_MODULE_DELETE_ACTION = ISSUE_MODULE + ISSUE_DELETE_ACTION;
export const ISSUE_MODULE_FILTER_ACTION = ISSUE_MODULE + ISSUE_FILER;
